### ISSUE TITLE
求《信息隐藏》资料

### ISSUE THREAD

**Issue by mmyyy22** [KangweiiLiu/UCAS_courses#1]
请问有《信息隐藏》课程资料吗？似乎并没有在仓库中找到，谢谢。

**Comment by KangweiiLiu** [comment]
你好！
赵老师会在第二节课或者第三节课发放课程讲义，同时赵老师会在每节课前半天发放课程PPT，其中基本涵盖所有的课程资料。
信息隐藏考试相关可以看readme中信息隐藏章节，如需课程PPT可留下邮箱。
